// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9dd443a5-d022-47d7-8d24-6e45387d39d3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Siwe55Jp2",
    "aws_user_pools_web_client_id": "6hj13j3nda2due3ed70ms266d9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://b6imjadesrgrthfcm7vurfvjgm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
